version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    tty: true
    image: jigintern/foodmates_server
    volumes:
      - ".:/go/src/github.com/jigintern/Foodmates-server"
    restart: always
    user: "${UID}:${GID}"

  db:
    container_name: mysql_host
    image: mysql:5.7
    volumes:
      - "./docker/db/data:/var/lib/mysql/"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./docker/db/sql:/docker-entrypoint-initdb.d/"
      - "./docker/log/mysql:/var/log/mysql"
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    tty: true
